// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dma_trig_model\convert.v
// Created: 2023-06-05 09:06:23
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: convert
// Source Path: dma_trig_model/dma_trig/convert
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module convert
          (datain,
           dataout_re,
           dataout_im);


  input   [31:0] datain;  // uint32
  output  signed [15:0] dataout_re;  // sfix16_En15
  output  signed [15:0] dataout_im;  // sfix16_En15


  wire [15:0] Bit_Slice_out1;  // uint16
  wire signed [15:0] Data_Type_Conversion1_out1;  // sfix16_En15
  wire [15:0] Bit_Slice1_out1;  // uint16
  wire signed [15:0] Data_Type_Conversion2_out1;  // sfix16_En15


  assign Bit_Slice_out1 = datain[31:16];



  assign Data_Type_Conversion1_out1 = Bit_Slice_out1;



  assign dataout_re = Data_Type_Conversion1_out1;

  assign Bit_Slice1_out1 = datain[15:0];



  assign Data_Type_Conversion2_out1 = Bit_Slice1_out1;



  assign dataout_im = Data_Type_Conversion2_out1;

endmodule  // convert

