// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dma_trig_model\rising.v
// Created: 2023-06-05 09:06:23
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rising
// Source Path: dma_trig_model/dma_trig/trigger/rising
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rising
          (clk,
           level,
           rising_1);


  input   clk;
  input   level;
  output  rising_1;


  reg  Delay3_out1;
  wire Bitwise_Operator3_out1;
  wire Bitwise_Operator2_out1;
  reg  Delay1_out1;

  initial begin
    Delay3_out1 = 1'b0;
    Delay1_out1 = 1'b0;
  end

  always @(posedge clk)
    begin : Delay3_process
      Delay3_out1 <= level;
    end



  assign Bitwise_Operator3_out1 =  ~ Delay3_out1;



  assign Bitwise_Operator2_out1 = Bitwise_Operator3_out1 & level;



  always @(posedge clk)
    begin : Delay1_process
      Delay1_out1 <= Bitwise_Operator2_out1;
    end



  assign rising_1 = Delay1_out1;

endmodule  // rising

