// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\dma_trig_model\Sample_and_Hold.v
// Created: 2023-06-05 09:06:23
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sample_and_Hold
// Source Path: dma_trig_model/dma_trig/trigger/Sample and Hold
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sample_and_Hold
          (clk,
           reset_x,
           In,
           Trigger,
           alpha);


  input   clk;
  input   reset_x;
  input   In;
  input   Trigger;
  output  alpha;


  reg  Trigger_delayed;
  wire Trigger_emulated;
  reg  In_hold;

  initial begin
    In_hold = 1'b0;
  end

  always @(posedge clk)
    begin : Trigger_delay
      Trigger_delayed <= Trigger;
    end

  assign Trigger_emulated = !Trigger_delayed && Trigger;

  always @(posedge clk)
    begin : alpha_hold_process
      if (Trigger_emulated) begin
        In_hold <= In;
      end
    end



  assign alpha = In_hold;

endmodule  // Sample_and_Hold

