#include "adrv9001.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.20.12*/
/* Firmware: v0.22.64*/
/* Profile Generator: v0.53.13.0*/
/* Stream Generator Assembly: v0.7.18.0*/
/* Transceiver Evaluation Software: v0.29.0*/
/* ADRV9001 Plugin: v0.29.0*/


#include "rf2_configure.h"
int rf2_configure(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;


	adi_adrv9001_RxrfdcLoidCfg_t loidConfig_1 = { 
		.loidEnable = false, 
		.loidThreshold_negdBFS = 61 };

	error_code = adi_adrv9001_Rx_Loid_Configure(adrv9001Device_0, ADI_CHANNEL_1, &loidConfig_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_GainControl_Configure(adrv9001Device_0, ADI_CHANNEL_1, &rf2_agcCfg_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint32_t gpIntMask = 0;
	error_code = adi_adrv9001_gpio_GpIntMask_Get(adrv9001Device_0, &gpIntMask);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_gpio_GpIntMask_Set(adrv9001Device_0, 16);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_AttenuationMode_Set(adrv9001Device_0, ADI_CHANNEL_1, ADI_ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_Attenuation_Set(adrv9001Device_0, ADI_CHANNEL_1, 10000);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_AttenuationMode_Set(adrv9001Device_0, ADI_CHANNEL_2, ADI_ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_Attenuation_Set(adrv9001Device_0, ADI_CHANNEL_2, 10000);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_RxInterfaceGainCtrl_t rxInterfaceGainConfig_1 = { 
		.updateInstance = ADI_ADRV9001_RX_INTERFACE_GAIN_UPDATE_TIMING_NOW, 
		.controlMode = ADI_ADRV9001_RX_INTERFACE_GAIN_CONTROL_MANUAL, 
		.gain = ADI_ADRV9001_RX_INTERFACE_GAIN_0_DB, 
		.rssiDuration = 255, 
		.rssiMovingAverageDuration = 10, 
		.gainControlAutomaticThreshold_dBFS = -2, 
		.signalPAR = 15, 
		.enableFastAttack = false };

	error_code = adi_adrv9001_Rx_InterfaceGain_Configure(adrv9001Device_0, ADI_CHANNEL_1, &rxInterfaceGainConfig_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PowerSavingAndMonitorMode_ChannelPowerSavingCfg_t powerSavingCfg_1 = { 
		.channelDisabledPowerDownMode = ADI_ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED, 
		.gpioPinPowerDownMode = ADI_ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED };

	error_code = adi_adrv9001_powerSavingAndMonitorMode_ChannelPowerSaving_Configure(adrv9001Device_0, ADI_CHANNEL_1, &powerSavingCfg_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_powerSavingAndMonitorMode_ChannelPowerSaving_Configure(adrv9001Device_0, ADI_CHANNEL_2, &powerSavingCfg_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_ChannelEnablementDelays_t delays_RX_1_2 = { 
		.riseToOnDelay = 1475, 
		.riseToAnalogOnDelay = 0, 
		.fallToOffDelay = 0, 
		.guardDelay = 0, 
		.holdDelay = 433152 };

	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &delays_RX_1_2);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_ChannelEnablementDelays_t delays_TX_1 = { 
		.riseToOnDelay = 170680, 
		.riseToAnalogOnDelay = 169206, 
		.fallToOffDelay = 170680, 
		.guardDelay = 0, 
		.holdDelay = 0 };

	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &delays_TX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &delays_TX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9010_bbdc_LoopGain_Set(adrv9001Device_0, ADI_CHANNEL_1, 65536);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9010_bbdc_LoopGain_Set(adrv9001Device_0, ADI_CHANNEL_2, 65536);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_TrackingCals_t trackingCals = { 
		.chanTrackingCalMask = { ADI_ADRV9001_TRACKING_CAL_TX_QEC | ADI_ADRV9001_TRACKING_CAL_TX_LO_LEAKAGE | ADI_ADRV9001_TRACKING_CAL_RX_QEC_WBPOLY | ADI_ADRV9001_TRACKING_CAL_ORX_QEC_WBPOLY | ADI_ADRV9001_TRACKING_CAL_RX_BBDC | ADI_ADRV9001_TRACKING_CAL_RX_RFDC | ADI_ADRV9001_TRACKING_CAL_RX_QEC_FIC | ADI_ADRV9001_TRACKING_CAL_RX_GAIN_CONTROL_DETECTORS | ADI_ADRV9001_TRACKING_CAL_RX_RSSI, ADI_ADRV9001_TRACKING_CAL_RX_BBDC | ADI_ADRV9001_TRACKING_CAL_RX_RFDC | ADI_ADRV9001_TRACKING_CAL_RX_QEC_FIC  } };

	error_code = adi_adrv9001_cals_Tracking_Set(adrv9001Device_0, &trackingCals);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_GainControl_Mode_Set(adrv9001Device_0, ADI_CHANNEL_1, ADI_ADRV9001_RX_GAIN_CONTROL_MODE_SPI);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_Gain_Set(adrv9001Device_0, ADI_CHANNEL_1, 247);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	

	return error_code;

}
