/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v68.13.7*/
/* Firmware: v0.22.30*/
/* Profile Generator: v0.53.6.0*/
/* Stream Generator Assembly: v0.7.11.0*/
/* Transceiver Evaluation Software: v0.26.0*/
/* ADRV9001 Plugin: v0.26.0*/

#ifndef _CALIBRATE_H_
#define _CALIBRATE_H_

#ifdef __cplusplus
extern "C" {
#endif
#include "adi_adrv9001_auxdac.h"
#include "adi_adrv9001_cals.h"
#include "adi_adrv9001_rx.h"
#include "adi_adrv9001_rx_gaincontrol.h"
#include "adi_adrv9001_spi.h"
#include "adi_adrv9001_ssi.h"
#include "adi_adrv9001_tx.h"
#include <stdlib.h>
extern adi_adrv9001_RxGainTableRow_t calibrate_gainTableRows_8[];
extern adi_adrv9001_RxGainTableRow_t calibrate_gainTableRows_10[];

#define ADI_HANDLE_ERROR(error_code) if (0 != error_code) { return error_code; }

int calibrate(adi_adrv9001_Device_t * adrv9001Device_0);

#ifdef __cplusplus
}
#endif

#endif
