/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v68.0.6*/
/* Firmware: v0.21.0.9*/
/* Profile Generator: v0.51.3.0*/
/* Stream Generator Assembly: v0.7.9.0*/
/* Transceiver Evaluation Software: v0.22.0*/
/* ADRV9001 Plugin: v0.22.0*/

#include "prime.h"

int prime(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;

	error_code = adi_adrv9001_Radio_Channel_ToPrimed(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1);
	error_code = adi_adrv9001_Radio_Channel_ToPrimed(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2);
	error_code = adi_adrv9001_Radio_Channel_ToPrimed(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1);
	error_code = adi_adrv9001_Radio_Channel_ToPrimed(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2);

	return error_code;
}
