#include "adrv9001.h"
#ifndef _RF1_INITIALIZE_H_
#define _RF1_INITIALIZE_H_

#ifdef __cplusplus
extern "C" {
#endif

/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.20.12*/
/* Firmware: v0.22.64*/
/* Profile Generator: v0.53.13.0*/
/* Stream Generator Assembly: v0.7.18.0*/
/* Transceiver Evaluation Software: v0.29.0*/
/* ADRV9001 Plugin: v0.29.0*/


#include "adi_adrv9001.h"
#include "adi_adrv9001_arm.h"
#include "adi_adrv9001_cals.h"
#include "adi_adrv9001_dpd.h"
#include "adi_adrv9001_gpio.h"
#include "adi_adrv9001_mcs.h"
#include "adi_adrv9001_powermanagement.h"
#include "adi_adrv9001_powersavingandmonitormode.h"
#include "adi_adrv9001_radio.h"
#include "adi_adrv9001_rx.h"
#include "adi_adrv9001_ssi.h"
#include "adi_adrv9001_stream.h"
#include "adi_adrv9001_tx.h"
#include <stdlib.h>

extern adi_adrv9001_Init_t rf1_init_2;
extern adi_adrv9001_RxGainTableRow_t rf1_gainTableRows_ORX_1_CORRECTION_TABLE[];
extern adi_adrv9001_RxGainTableRow_t rf1_gainTableRows_ORX_2_CORRECTION_TABLE[];
extern adi_adrv9001_RxGainTableRow_t rf1_gainTableRows_RX_1_CORRECTION_TABLE[];
extern adi_adrv9001_RxGainTableRow_t rf1_gainTableRows_RX_2_CORRECTION_TABLE[];
extern adi_adrv9001_TxAttenTableRow_t rf1_attenTableRows[];
extern adi_adrv9001_GpioCtrlInitCfg_t rf1_gpioCtrlInitCfg;
#define ADI_HANDLE_ERROR(error_code, device_context) if (0 != error_code) \
{ \
    printf("Device API call returned non-zero error code\n"); \
    printf("error_code: %d \n", error_code); \
    printf("Error source: %d \n", device_context->common.error.errSource); \
    printf("Error number: %d \n", device_context->common.error.errCode); \
    printf("In file: %s \n", device_context->common.error.errFile); \
    printf("In function: %s \n", device_context->common.error.errFunc); \
    printf("On line: %d \n", device_context->common.error.errLine); \
    printf("Variable name: %s \n", device_context->common.error.varName); \
    printf("Error message: %s \n", device_context->common.error.errormessage); \
}
int rf1_initialize(adi_adrv9001_Device_t * adrv9001Device_0);


#ifdef __cplusplus
}
#endif

#endif

