/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.20.12*/
/* Firmware: v0.22.64*/
/* Profile Generator: v0.53.13.0*/
/* Stream Generator Assembly: v0.7.18.0*/
/* Transceiver Evaluation Software: v0.29.0*/
/* ADRV9001 Plugin: v0.29.0*/


#include "rf1_calibrate.h"
int rf1_calibrate(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;


	adi_adrv9001_InitCals_t initCals_ADRV9001_ALL = { 
		.sysInitCalMask = (adi_adrv9001_InitCalibrations_e) 0, 
		.chanInitCalMask = { ADI_ADRV9001_INIT_CAL_TX_QEC | ADI_ADRV9001_INIT_CAL_TX_LO_LEAKAGE | ADI_ADRV9001_INIT_CAL_TX_LB_PD | ADI_ADRV9001_INIT_CAL_TX_BBAF | ADI_ADRV9001_INIT_CAL_TX_BBAF_GD | ADI_ADRV9001_INIT_CAL_TX_ATTEN_DELAY | ADI_ADRV9001_INIT_CAL_TX_DAC | ADI_ADRV9001_INIT_CAL_TX_PATH_DELAY | ADI_ADRV9001_INIT_CAL_RX_HPADC_FLASH | ADI_ADRV9001_INIT_CAL_RX_LPADC | ADI_ADRV9001_INIT_CAL_RX_TIA_CUTOFF | ADI_ADRV9001_INIT_CAL_RX_GROUP_DELAY | ADI_ADRV9001_INIT_CAL_RX_QEC_TCAL | ADI_ADRV9001_INIT_CAL_RX_QEC_FIC | ADI_ADRV9001_INIT_CAL_RX_RF_DC_OFFSET | ADI_ADRV9001_INIT_CAL_RX_GAIN_PATH_DELAY, ADI_ADRV9001_INIT_CAL_TX_QEC | ADI_ADRV9001_INIT_CAL_TX_LO_LEAKAGE | ADI_ADRV9001_INIT_CAL_TX_LB_PD | ADI_ADRV9001_INIT_CAL_TX_BBAF | ADI_ADRV9001_INIT_CAL_TX_BBAF_GD | ADI_ADRV9001_INIT_CAL_TX_ATTEN_DELAY | ADI_ADRV9001_INIT_CAL_TX_DAC | ADI_ADRV9001_INIT_CAL_TX_PATH_DELAY | ADI_ADRV9001_INIT_CAL_RX_HPADC_FLASH | ADI_ADRV9001_INIT_CAL_RX_LPADC | ADI_ADRV9001_INIT_CAL_RX_TIA_CUTOFF | ADI_ADRV9001_INIT_CAL_RX_GROUP_DELAY | ADI_ADRV9001_INIT_CAL_RX_QEC_FIC | ADI_ADRV9001_INIT_CAL_RX_RF_DC_OFFSET | ADI_ADRV9001_INIT_CAL_RX_GAIN_PATH_DELAY  }, 
		.calMode = ADI_ADRV9001_INIT_CAL_MODE_ALL, 
		.force = false };

	uint8_t errorFlag_ADRV9001_ALL = 0;
	error_code = adi_adrv9001_cals_InitCals_Run(adrv9001Device_0, &initCals_ADRV9001_ALL, 300000, &errorFlag_ADRV9001_ALL);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_spi_Byte_Read(adrv9001Device_0, 11, &errorFlag_ADRV9001_ALL);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint32_t internalPathDelays_ns_RX_1[6] = { 0 };
	error_code = adi_adrv9001_cals_InternalPathDelay_Get(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, internalPathDelays_ns_RX_1, 6);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint32_t internalPathDelays_ns_TX_1[6] = { 0 };
	error_code = adi_adrv9001_cals_InternalPathDelay_Get(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, internalPathDelays_ns_TX_1, 6);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint32_t internalPathDelays_ns_TX_2[6] = { 0 };
	error_code = adi_adrv9001_cals_InternalPathDelay_Get(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, internalPathDelays_ns_TX_2, 6);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint8_t minGainIndex_1 = 187;
	uint8_t maxGainIndex_1 = 255;
	error_code = adi_adrv9001_Rx_GainControl_MinMaxGainIndex_Get(adrv9001Device_0, ADI_CHANNEL_1, &minGainIndex_1, &maxGainIndex_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	uint16_t numGainIndicesRead_1 = 0;
	error_code = adi_adrv9001_Rx_GainTable_Read(adrv9001Device_0, ADI_CHANNEL_1, 255, rf1_gainTableRows_1, 69, &numGainIndicesRead_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_DataPath_Loopback_Set(adrv9001Device_0, ADI_CHANNEL_1, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_Loopback_Set(adrv9001Device_0, ADI_CHANNEL_1, ADI_ADRV9001_SSI_TYPE_LVDS, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_DataPath_Loopback_Set(adrv9001Device_0, ADI_CHANNEL_2, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_Loopback_Set(adrv9001Device_0, ADI_CHANNEL_2, ADI_ADRV9001_SSI_TYPE_LVDS, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	

	return error_code;

}
