#include "adrv9001.h"
#include "FreeRTOS.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.20.12*/
/* Firmware: v0.22.64*/
/* Profile Generator: v0.53.13.0*/
/* Stream Generator Assembly: v0.7.18.0*/
/* Transceiver Evaluation Software: v0.29.0*/
/* ADRV9001 Plugin: v0.29.0*/


#include "rf1_initialize.h"
int rf1_initialize(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;


	/* Begin region  IAdrv9001BoardEe.Initialize(initializationParameters, phase) */
	
	error_code = adi_adrv9001_HwClose(adrv9001Device_0);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_SpiSettings_t spiSettings = { 
		.msbFirst = 1, 
		.enSpiStreaming = 0, 
		.autoIncAddrUp = 1, 
		.fourWireMode = 1, 
		.cmosPadDrvStrength = ADI_ADRV9001_CMOSPAD_DRV_STRONG };

	error_code = adi_adrv9001_HwOpen(adrv9001Device_0, &spiSettings);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_HwReset(adrv9001Device_0);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_InitAnalog(adrv9001Device_0, &rf1_init_2, ADI_ADRV9001_DEVICECLOCKDIVISOR_2);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_AhbSpiBridge_Enable(adrv9001Device_0);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);	
	
	FRESULT fr;
	UINT br; // Bytes read
	FIL stream_binary_STANDARD_BYTES_252_FILE;
	int64_t stream_binary_STANDARD_BYTES_252_FILE_SIZE;
	uint8_t* stream_binary_STANDARD_BYTES_252;
	fr = f_open(&stream_binary_STANDARD_BYTES_252_FILE, "stream_binary_STANDARD_BYTES_252.bin", FA_OPEN_EXISTING | FA_READ);
	if( fr == FR_OK )
	{
		stream_binary_STANDARD_BYTES_252_FILE_SIZE = f_size(&stream_binary_STANDARD_BYTES_252_FILE);
	    stream_binary_STANDARD_BYTES_252 = (uint8_t*) pvPortMalloc(sizeof(uint8_t) * stream_binary_STANDARD_BYTES_252_FILE_SIZE);
	    if (stream_binary_STANDARD_BYTES_252 != NULL) {
	        f_read(&stream_binary_STANDARD_BYTES_252_FILE, stream_binary_STANDARD_BYTES_252, stream_binary_STANDARD_BYTES_252_FILE_SIZE, &br);
	    }
	    f_close(&stream_binary_STANDARD_BYTES_252_FILE);
	}
	
	error_code = adi_adrv9001_Stream_Image_Write(adrv9001Device_0, 0, stream_binary_STANDARD_BYTES_252, 32768, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);	
	
	FIL arm_binary_STANDARD_BYTES_252_FILE;
	int64_t arm_binary_STANDARD_BYTES_252_FILE_SIZE;
	uint8_t* arm_binary_STANDARD_BYTES_252;
	fr = f_open(&arm_binary_STANDARD_BYTES_252_FILE, "arm_binary_STANDARD_BYTES_252.bin", FA_OPEN_EXISTING | FA_READ);
	if( fr == FR_OK )
	{
		arm_binary_STANDARD_BYTES_252_FILE_SIZE = f_size(&arm_binary_STANDARD_BYTES_252_FILE);
	    arm_binary_STANDARD_BYTES_252 = (uint8_t*) pvPortMalloc(sizeof(uint8_t) * arm_binary_STANDARD_BYTES_252_FILE_SIZE);
	    if (arm_binary_STANDARD_BYTES_252 != NULL) {
	        f_read(&arm_binary_STANDARD_BYTES_252_FILE, arm_binary_STANDARD_BYTES_252, arm_binary_STANDARD_BYTES_252_FILE_SIZE, &br);
	    }
	    f_close(&arm_binary_STANDARD_BYTES_252_FILE);
	}
	
	error_code = adi_adrv9001_arm_Image_Write(adrv9001Device_0, 0, arm_binary_STANDARD_BYTES_252, 310272, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_Profile_Write(adrv9001Device_0, &rf1_init_2);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_PfirProfiles_Write(adrv9001Device_0, &rf1_init_2);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_RxLnaConfig_t lnaConfig_ORX_1_CORRECTION_TABLE = { 
		.externalLnaPresent = false, 
		.gpioSourceSel = ADI_ADRV9001_GPIO_ANALOG_PIN_NIBBLE_UNASSIGNED, 
		.externalLnaPinSel = ADI_ADRV9001_EXTERNAL_LNA_PIN_RX1_LOWER_RX2_UPPER, 
		.settlingDelay = 0, 
		.numberLnaGainSteps = 0, 
		.lnaGainSteps_mdB = { 0 }, 
		.lnaDigitalGainDelay = 0, 
		.minGainIndex = 0, 
		.lnaType = ADI_ADRV9001_EXTERNAL_LNA_TYPE_SINGLE };

	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_1, 14, rf1_gainTableRows_ORX_1_CORRECTION_TABLE, 13, &lnaConfig_ORX_1_CORRECTION_TABLE, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_2, 14, rf1_gainTableRows_ORX_2_CORRECTION_TABLE, 13, &lnaConfig_ORX_1_CORRECTION_TABLE, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, 255, rf1_gainTableRows_RX_1_CORRECTION_TABLE, 69, &lnaConfig_ORX_1_CORRECTION_TABLE, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, 255, rf1_gainTableRows_RX_2_CORRECTION_TABLE, 69, &lnaConfig_ORX_1_CORRECTION_TABLE, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_AttenuationTable_Write(adrv9001Device_0, 3, 0, rf1_attenTableRows, 960);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PowerManagementSettings_t powerManagementSettings = { 
		.ldoPowerSavingModes = { ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1 } };

	error_code = adi_adrv9001_powermanagement_Configure(adrv9001Device_0, &powerManagementSettings);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_Start(adrv9001Device_0);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_StartStatus_Check(adrv9001Device_0, 5000000);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_OutputPowerBoost_Set(adrv9001Device_0, ADI_CHANNEL_1, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_OutputPowerBoost_Set(adrv9001Device_0, ADI_CHANNEL_2, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_SsiCalibrationCfg_t ssiCalibration_1_LVDS = { 
		.rxClkDelay = { 0 }, 
		.rxStrobeDelay = { 0 }, 
		.rxIDataDelay = { 0 }, 
		.rxQDataDelay = { 0 }, 
		.txClkDelay = { 0 }, 
		.txRefClkDelay = { 0 }, 
		.txStrobeDelay = { 0 }, 
		.txIDataDelay = { 0 }, 
		.txQDataDelay = { 0 } };

	error_code = adi_adrv9001_Ssi_Delay_Configure(adrv9001Device_0, ADI_CHANNEL_1, ADI_ADRV9001_SSI_TYPE_LVDS, &ssiCalibration_1_LVDS);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_Delay_Configure(adrv9001Device_0, ADI_CHANNEL_2, ADI_ADRV9001_SSI_TYPE_LVDS, &ssiCalibration_1_LVDS);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_gpio_ControlInit_Configure(adrv9001Device_0, &rf1_gpioCtrlInitCfg);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PllLoopFilterCfg_t pllLoopFilterConfig_LO1 = { 
		.effectiveLoopBandwidth_kHz = 0, 
		.loopBandwidth_kHz = 300, 
		.phaseMargin_degrees = 60, 
		.powerScale = 5, 
		.loopCoefficientMode = ADI_ADRV9001_PLL_LF_COEFFICIENT_CALCULATE };

	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &pllLoopFilterConfig_LO1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &pllLoopFilterConfig_LO1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_AUX, &pllLoopFilterConfig_LO1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PowerSavingAndMonitorMode_MonitorModeRssiCfg_t monitorModeRssiCfg = { 
		.numberOfMeasurementsToAverage = 4, 
		.measurementsStartPeriod_ms = 1, 
		.detectionThreshold_mdBFS = -80000, 
		.measurementDuration_samples = 10 };

	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_Rssi_Configure(adrv9001Device_0, &monitorModeRssiCfg);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PowerSavingAndMonitorMode_MonitorModeDmrSearchCfg_t dmrSearchCfg = { 
		.pathDelay = 0, 
		.magcorrTh = 250, 
		.detCnt1 = 375, 
		.detCnt2 = 500, 
		.detTgtMin = 880000 };

	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_DmrSearch_Configure(adrv9001Device_0, &dmrSearchCfg);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_RxPortSwitchCfg_t switchConfig = { 
		.minFreqPortA_Hz = 890000000, 
		.maxFreqPortA_Hz = 910000000, 
		.minFreqPortB_Hz = 1890000000, 
		.maxFreqPortB_Hz = 1910000000, 
		.enable = false, 
		.manualRxPortSwitch = false };

	error_code = adi_adrv9001_Rx_PortSwitch_Configure(adrv9001Device_0, &switchConfig);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_Carrier_t carrier_RX_1 = { 
		.loGenOptimization = ADI_ADRV9001_LO_GEN_OPTIMIZATION_PHASE_NOISE, 
		.carrierFrequency_Hz = 157200000, 
		.intermediateFrequency_Hz = 0, 
		.manualRxport = ADI_ADRV9001_RX_A };

	error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &carrier_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_ChannelEnablementDelays_t delays_RX_1 = { 
		.riseToOnDelay = 0, 
		.riseToAnalogOnDelay = 0, 
		.fallToOffDelay = 0, 
		.guardDelay = 0, 
		.holdDelay = 0 };

	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &delays_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Rx_AdcSwitchEnable_Set(adrv9001Device_0, ADI_CHANNEL_1, false);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &carrier_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &delays_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_cals_ExternalPathDelay_Set(adrv9001Device_0, ADI_CHANNEL_1, 0);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_SlewRateLimiterCfg_t config_1 = { 
		.srlEnable = false, 
		.srlStatisticsEnable = false, 
		.srlTableSelect = ADI_ADRV9001_SRL_TABLE0, 
		.srlSlewOffset = 0, 
		.srlStatisticsMode = ADI_ADRV9001_SRL_STATISTICS_MIN_SLEW_FACTOR_OBSERVED };

	error_code = adi_adrv9001_Tx_SlewRateLimiter_Configure(adrv9001Device_0, ADI_CHANNEL_1, &config_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &carrier_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &delays_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_cals_ExternalPathDelay_Set(adrv9001Device_0, ADI_CHANNEL_2, 223500);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Tx_SlewRateLimiter_Configure(adrv9001Device_0, ADI_CHANNEL_2, &config_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_DpdInitCfg_t dpdConfig_2 = { 
		.enable = true, 
		.amplifierType = ADI_ADRV9001_DPDAMPLIFIER_DEFAULT, 
		.lutSize = ADI_ADRV9001_DPDLUTSIZE_512, 
		.model = ADI_ADRV9001_DPDMODEL_4, 
		.changeModelTapOrders = false, 
		.modelOrdersForEachTap = { 31, 127, 31, 30  }, 
		.preLutScale = 8, 
		.clgcEnable = 0 };

	error_code = adi_adrv9001_dpd_Initial_Configure(adrv9001Device_0, ADI_CHANNEL_2, &dpdConfig_2);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_PllConfig_t pllConfig_LO1 = { 
		.pllCalibration = ADI_ADRV9001_PLL_CALIBRATION_NORMAL, 
		.pllPower = ADI_ADRV9001_PLL_POWER_LOW };

	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &pllConfig_LO1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &pllConfig_LO1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_McsDelay_t mcsDelay_RX_1 = { 
		.readDelay = 1, 
		.sampleDelay = 0 };

	error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &mcsDelay_RX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	adi_adrv9001_McsDelay_t mcsDelay_TX_1 = { 
		.readDelay = 5, 
		.sampleDelay = 0 };

	error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &mcsDelay_TX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &mcsDelay_TX_1);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
	error_code = adi_adrv9001_arm_System_Program(adrv9001Device_0, 45);
	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	

	
	
	/* End region  IAdrv9001BoardEe.Initialize(initializationParameters, phase) */

	

	return error_code;

}
