ipx::merge_project_changes hdl_parameters [ipx::current_core]

ipx::add_user_parameter RSTN_ENABLE [ipx::current_core]
set_property value_resolve_type user [ipx::get_user_parameters RSTN_ENABLE -of_objects [ipx::current_core]]
ipgui::add_param -name {RSTN_ENABLE} -component [ipx::current_core]
set_property display_name {RSTN Enable} [ipgui::get_guiparamspec -name "RSTN_ENABLE" -component [ipx::current_core] ]
set_property widget {checkBox} [ipgui::get_guiparamspec -name "RSTN_ENABLE" -component [ipx::current_core] ]
set_property value true [ipx::get_user_parameters RSTN_ENABLE -of_objects [ipx::current_core]]
set_property value_format bool [ipx::get_user_parameters RSTN_ENABLE -of_objects [ipx::current_core]]
set_property enablement_resolve_type dependent [ipx::get_ports rstn -of_objects [ipx::current_core]]
set_property enablement_dependency spirit:decode(id('PARAM_VALUE.RSTN_ENABLE'))>0 [ipx::get_ports rstn -of_objects [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 0 [ipgui::get_guiparamspec -name "RSTN_ENABLE" -component [ipx::current_core]] -parent [ipgui::get_pagespec -name "Page 0" -component [ipx::current_core]]

ipx::add_user_parameter SYS_TICKS_ENABLE [ipx::current_core]
set_property value_resolve_type user [ipx::get_user_parameters SYS_TICKS_ENABLE -of_objects [ipx::current_core]]
ipgui::add_param -name {SYS_TICKS_ENABLE} -component [ipx::current_core]
set_property display_name {Sys Ticks Enable} [ipgui::get_guiparamspec -name "SYS_TICKS_ENABLE" -component [ipx::current_core] ]
set_property widget {checkBox} [ipgui::get_guiparamspec -name "SYS_TICKS_ENABLE" -component [ipx::current_core] ]
set_property value true [ipx::get_user_parameters SYS_TICKS_ENABLE -of_objects [ipx::current_core]]
set_property value_format bool [ipx::get_user_parameters SYS_TICKS_ENABLE -of_objects [ipx::current_core]]
set_property enablement_resolve_type dependent [ipx::get_ports sys_ticks -of_objects [ipx::current_core]]
set_property enablement_dependency {$SYS_TICKS_ENABLE>0} [ipx::get_ports sys_ticks -of_objects [ipx::current_core]]
ipgui::move_param -component [ipx::current_core] -order 0 [ipgui::get_guiparamspec -name "SYS_TICKS_ENABLE" -component [ipx::current_core]] -parent [ipgui::get_pagespec -name "Page 0" -component [ipx::current_core]]
