#include "adrv9001.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.16.2*/
/* Firmware: v0.22.49*/
/* Profile Generator: v0.53.11.0*/
/* Stream Generator Assembly: v0.7.15.0*/
/* Transceiver Evaluation Software: v0.28.0*/
/* ADRV9001 Plugin: v0.28.0*/


#include "rf1_initialize.h"
//int rf1_initialize_new( adi_adrv9001_Device_t * adrv9001Device_0, adrv9001_profile_t *ProfileInstance )
int rf1_initialize_new( adrv9001_t *Instance, adrv9001_profile_t *ProfileInstance )
{
	int32_t error_code = 0;
	adi_adrv9001_Device_t * adrv9001Device_0 = &Instance->Device;

	bool Tx1ProfileEnable = ((Instance->Params->tx.txInitChannelMask & ADI_ADRV9001_TX1 ) == ADI_ADRV9001_TX1 );
	bool Tx2ProfileEnable = ((Instance->Params->tx.txInitChannelMask & ADI_ADRV9001_TX2 ) == ADI_ADRV9001_TX2 );
	bool Rx1ProfileEnable = ((Instance->Params->rx.rxInitChannelMask & ADI_ADRV9001_RX1 ) == ADI_ADRV9001_RX1 );
	bool Rx2ProfileEnable = ((Instance->Params->rx.rxInitChannelMask & ADI_ADRV9001_RX2 ) == ADI_ADRV9001_RX2 );

	adi_common_ApiVersion_t apiVersion_0 = { 
		.major = 0, 
		.minor = 0, 
		.patch = 0 };

	error_code = adi_adrv9001_ApiVersion_Get(adrv9001Device_0, &apiVersion_0);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	/* Begin region  Adrv9001BoardEe.Initialize(init, radioCtrlInit, streamImageBytes, armImage, orxGainTable, rxGainTable, txAttenTable, phase, emulatedPartNumber) */

	error_code = adi_adrv9001_HwClose(adrv9001Device_0);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	adi_adrv9001_SpiSettings_t spiSettings_6 = { 
		.msbFirst = 1, 
		.enSpiStreaming = 0, 
		.autoIncAddrUp = 1, 
		.fourWireMode = 1, 
		.cmosPadDrvStrength = ADI_ADRV9001_CMOSPAD_DRV_STRONG };

	error_code = adi_adrv9001_HwOpen(adrv9001Device_0, &spiSettings_6);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_HwReset(adrv9001Device_0);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_InitAnalog(adrv9001Device_0, &rf1_initialize_init_8, ADI_ADRV9001_DEVICECLOCKDIVISOR_2);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_AhbSpiBridge_Enable(adrv9001Device_0);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_Stream_Image_Write(adrv9001Device_0, 0, rf1_initialize_binary_10, 32768, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_Image_Write(adrv9001Device_0, 0, rf1_initialize_binary_11, 310272, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_Profile_Write(adrv9001Device_0, &rf1_initialize_init_8);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_PfirProfiles_Write(adrv9001Device_0, &rf1_initialize_init_8);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	/*
	adi_adrv9001_RxLnaConfig_t lnaConfig_14 = { 
		.externalLnaPresent = false, 
		.gpioSourceSel = ADI_ADRV9001_GPIO_ANALOG_PIN_NIBBLE_UNASSIGNED, 
		.externalLnaPinSel = ADI_ADRV9001_EXTERNAL_LNA_PIN_RX1_LOWER_RX2_UPPER, 
		.settlingDelay = 0, 
		.numberLnaGainSteps = 0, 
		.lnaGainSteps_mdB = { 0 }, 
		.lnaDigitalGainDelay = 0, 
		.minGainIndex = 0, 
		.lnaType = ADI_ADRV9001_EXTERNAL_LNA_TYPE_SINGLE };
    */


	error_code = adi_adrv9001_Tx_AttenuationTable_Write(adrv9001Device_0, 3, 0, rf1_initialize_attenTableRows_18, 960);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	adi_adrv9001_PowerManagementSettings_t powerManagementSettings_19 = { 
		.ldoPowerSavingModes = { ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1 } };

	error_code = adi_adrv9001_powermanagement_Configure(adrv9001Device_0, &powerManagementSettings_19);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_Start(adrv9001Device_0);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_arm_StartStatus_Check(adrv9001Device_0, 5000000);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);




	adi_adrv9001_SsiCalibrationCfg_t ssiCalibration_25 = { 
		.rxClkDelay = { 0 }, 
		.rxStrobeDelay = { 0 }, 
		.rxIDataDelay = { 0 }, 
		.rxQDataDelay = { 0 }, 
		.txClkDelay = { 0 }, 
		.txRefClkDelay = { 0 }, 
		.txStrobeDelay = { 0 }, 
		.txIDataDelay = { 0 }, 
		.txQDataDelay = { 0 } };

	error_code = adi_adrv9001_Ssi_Delay_Configure(adrv9001Device_0, ADI_ADRV9001_SSI_TYPE_LVDS, &ssiCalibration_25);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	adi_adrv9001_GpioCtrlInitCfg_t gpioCtrlInitCfg_26 = { 
		.tx_ext_frontend_ctrl = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.rx_ext_frontend_ctrl = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.ext_pll_chip_enable = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.vco_chip_enable = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.ext_pll_lock = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.channelPowerSaving = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.systemPowerSavingAndMonitorEnable = { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, 
		.systemPowerSavingAndMonitorWakeUp = { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, 
		.fh_update_rx_nco = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  }, 
		.rx_interfaceGain_seed_save = { { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }, { 
		.pin = ADI_ADRV9001_GPIO_UNASSIGNED, 
		.polarity = ADI_ADRV9001_GPIO_POLARITY_NORMAL, 
		.master = ADI_ADRV9001_GPIO_MASTER_BBIC }  } };

	error_code = adi_adrv9001_gpio_ControlInit_Configure(adrv9001Device_0, &gpioCtrlInitCfg_26);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &ProfileInstance->pll_lo1_loop_filter);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &ProfileInstance->pll_lo2_loop_filter);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_AUX, &ProfileInstance->pll_aux_loop_filter);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_Rssi_Configure(adrv9001Device_0, &ProfileInstance->MonitorModeRssiCfg);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	adi_adrv9001_PowerSavingAndMonitorMode_MonitorModeDmrSearchCfg_t dmrSearchCfg_31 = { 
		.pathDelay = 0, 
		.magcorrTh = 250, 
		.detCnt1 = 375, 
		.detCnt2 = 500, 
		.detTgtMin = 880000 };

	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_DmrSearch_Configure(adrv9001Device_0, &dmrSearchCfg_31);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_Rx_PortSwitch_Configure(adrv9001Device_0, &ProfileInstance->RxPortSwitchCfg);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	if(Rx1ProfileEnable == true)
	{
		error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, 255, rf1_initialize_gainTableRows_16, 69, &ProfileInstance->Rx1Profile->lnaConfig, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_1, 14, rf1_initialize_gainTableRows_14, 13, &ProfileInstance->oRx1Profile->lnaConfig, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &ProfileInstance->Rx1Carrier);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &ProfileInstance->Rx1EnablementDelays);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Rx_AdcSwitchEnable_Set(adrv9001Device_0, ADI_CHANNEL_1, false);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

		error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &ProfileInstance->Rx1McsDelay);
		ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	}
	if(Rx2ProfileEnable == true)
    {

	  error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_2, 14, rf1_initialize_gainTableRows_15, 13, &ProfileInstance->oRx2Profile->lnaConfig, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	  error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, 255, rf1_initialize_gainTableRows_17, 69, &ProfileInstance->Rx2Profile->lnaConfig, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	  error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, &ProfileInstance->Rx2Carrier);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, &ProfileInstance->Rx2EnablementDelays);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Rx_AdcSwitchEnable_Set(adrv9001Device_0, ADI_CHANNEL_2, false);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

      error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &ProfileInstance->Rx2McsDelay);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
    }
    if(Tx1ProfileEnable == true)
    {
      error_code = adi_adrv9001_Tx_OutputPowerBoost_Set(adrv9001Device_0, ADI_CHANNEL_1, ProfileInstance->Tx1Boost);
      ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	  error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &ProfileInstance->Tx1Carrier);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &ProfileInstance->Tx1EnablementDelays);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_cals_ExternalPathDelay_Set(adrv9001Device_0, ADI_CHANNEL_1, ProfileInstance->Tx1DpdExternalPathDelay);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	  error_code = adi_adrv9001_Tx_SlewRateLimiter_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Tx1SlewRateLimiterCfg);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
  
      if( ProfileInstance->Tx1DpdInitCfg.enable == true)
      {
    	error_code = adi_adrv9001_dpd_Initial_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Tx1DpdInitCfg);

	    ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
      }

  	  error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, &ProfileInstance->Tx1McsDelay);

  	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	
    }
    if(Tx2ProfileEnable == true)
    {
      error_code = adi_adrv9001_Tx_OutputPowerBoost_Set(adrv9001Device_0, ADI_CHANNEL_2, ProfileInstance->Tx2Boost);
      ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	  error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &ProfileInstance->Tx2Carrier);

  	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &ProfileInstance->Tx2EnablementDelays);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_cals_ExternalPathDelay_Set(adrv9001Device_0, ADI_CHANNEL_2, ProfileInstance->Tx2DpdExternalPathDelay);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  error_code = adi_adrv9001_Tx_SlewRateLimiter_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Tx2SlewRateLimiterCfg);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	  if( ProfileInstance->Tx2DpdInitCfg.enable == true)
      {
	    error_code = adi_adrv9001_dpd_Initial_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Tx2DpdInitCfg);

	    ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
      }
	  error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &ProfileInstance->Tx2McsDelay);

	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
    }
	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &ProfileInstance->Lo1PllConfig);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &ProfileInstance->Lo2PllConfig);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_arm_System_Program(adrv9001Device_0, 15);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	/* End region  Adrv9001BoardEe.Initialize(init, radioCtrlInit, streamImageBytes, armImage, orxGainTable, rxGainTable, txAttenTable, phase, emulatedPartNumber) */


	

	return error_code;

}
