#include "adrv9001.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* The generation process is deterministic and tested (not generative AI), */
/* but not every scenario or risk has been captured in unit tests. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver: v68.16.2*/
/* Firmware: v0.22.49*/
/* Profile Generator: v0.53.11.0*/
/* Stream Generator Assembly: v0.7.15.0*/
/* Transceiver Evaluation Software: v0.28.0*/
/* ADRV9001 Plugin: v0.28.0*/


#include "rf1_configure.h"
//int rf1_configure_new(adi_adrv9001_Device_t * adrv9001Device_0, adrv9001_profile_t *ProfileInstance)
int rf1_configure_new(adrv9001_t *Instance, adrv9001_profile_t *ProfileInstance)
{
	int32_t error_code = 0;
	adi_adrv9001_Device_t * adrv9001Device_0 = &Instance->Device;

	bool Tx1ProfileEnable = ((Instance->Params->tx.txInitChannelMask & ADI_ADRV9001_TX1 ) == ADI_ADRV9001_TX1 );
	bool Tx2ProfileEnable = ((Instance->Params->tx.txInitChannelMask & ADI_ADRV9001_TX2 ) == ADI_ADRV9001_TX2 );
	bool Rx1ProfileEnable = ((Instance->Params->rx.rxInitChannelMask & ADI_ADRV9001_RX1 ) == ADI_ADRV9001_RX1 );
	bool Rx2ProfileEnable = ((Instance->Params->rx.rxInitChannelMask & ADI_ADRV9001_RX2 ) == ADI_ADRV9001_RX2 );

    if(Rx1ProfileEnable == true)
    {
    	error_code = adi_adrv9001_Rx_Loid_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Rx1LoidCfg);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_GainControl_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Rx1Agc);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_InterfaceGain_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Rx1InterfaceGainCfg);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, &ProfileInstance->Rx1EnablementDelays);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_GainControl_Mode_Set(adrv9001Device_0, ADI_CHANNEL_1, ProfileInstance->Rx1AgcCtrlMode);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_Gain_Set(adrv9001Device_0, ADI_CHANNEL_1, 247);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
    }
    if(Rx2ProfileEnable == true)
    {
    	error_code = adi_adrv9001_Rx_Loid_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Rx2LoidCfg);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_GainControl_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Rx2Agc);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_InterfaceGain_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Rx2InterfaceGainCfg);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, &ProfileInstance->Rx2EnablementDelays);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_GainControl_Mode_Set(adrv9001Device_0, ADI_CHANNEL_2, ProfileInstance->Rx2AgcCtrlMode);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Rx_Gain_Set(adrv9001Device_0, ADI_CHANNEL_2, 247);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
    }
    if(Tx1ProfileEnable == true)
    {
    	error_code = adi_adrv9001_Tx_AttenuationMode_Set(adrv9001Device_0, ADI_CHANNEL_1, ADI_ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Tx_Attenuation_Set(adrv9001Device_0, ADI_CHANNEL_1, 10000);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_1, &ProfileInstance->Tx1EnablementDelays);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	if( ProfileInstance->Tx1DpdInitCfg.enable == true)
        {
    	  error_code = adi_adrv9001_dpd_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Tx1DpdCfg);

    	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
        }
    }
    if(Tx2ProfileEnable == true)
    {
    	error_code = adi_adrv9001_Tx_AttenuationMode_Set(adrv9001Device_0, ADI_CHANNEL_2, ADI_ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Tx_Attenuation_Set(adrv9001Device_0, ADI_CHANNEL_2, 10000);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &ProfileInstance->Tx2EnablementDelays);
    	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

    	if( ProfileInstance->Tx2DpdInitCfg.enable == true)
    	{
          error_code = adi_adrv9001_dpd_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Tx2DpdCfg);

    	  ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
    	}
    }

	uint32_t gpIntMask_5 = 0;
	error_code = adi_adrv9001_gpio_GpIntMask_Get(adrv9001Device_0, &gpIntMask_5);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_gpio_GpIntMask_Set(adrv9001Device_0, 16);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_powerSavingAndMonitorMode_ChannelPowerSaving_Configure(adrv9001Device_0, ADI_CHANNEL_1, &ProfileInstance->Ch1PowerSavingCfg);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9001_powerSavingAndMonitorMode_ChannelPowerSaving_Configure(adrv9001Device_0, ADI_CHANNEL_2, &ProfileInstance->Ch2PowerSavingCfg);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9010_bbdc_LoopGain_Set(adrv9001Device_0, ADI_CHANNEL_1, 65536);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);
	error_code = adi_adrv9010_bbdc_LoopGain_Set(adrv9001Device_0, ADI_CHANNEL_2, 65536);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	error_code = adi_adrv9001_cals_Tracking_Set(adrv9001Device_0, &ProfileInstance->TrackingCals);

	ADI_HANDLE_ERROR(error_code, adrv9001Device_0);

	return error_code;

}
