% This file contains code automatically generated by a machine.
% It has not been independently verified by any human.
% All code is provided as-is for example purposes only.
% The customer assumes all risks related to the use of this code.


% Transceiver Name: ADRV9002
% Silicon Revision: C0
% Evaluation Board Revision: 2B
% Tx / Rx optimal carrier frequencies: 30 MHz to 3 GHz
% External LO optimal frequencies: 60 MHz to 6 GHz
% 
% FPGA: v8.2.21
% Device Driver API: v48.49.2
% Device Driver Client: v48.49.2
% Firmware: v0.20.0.10
% Profile Generator: v0.50.5.0
% Stream Generator Assembly: v0.7.9.0
% Transceiver Evaluation Software: v0.20.0
% ADRV9001 Plugin: v0.20.0

function Adrv9001_StopTransmitting( obj ) % obj.fpga9001Device)

	INSTALL_DIRECTORY = 'C:/Program Files/Analog Devices/ADRV9001 Transceiver Evaluation Software/';
	CLIENT_DIRECTORY = 'C:/Program Files/Analog Devices/ADRV9001 Transceiver Evaluation Software/';
	NET.addAssembly([INSTALL_DIRECTORY 'AnalogDevices.Peitho.dll']);
	NET.addAssembly([INSTALL_DIRECTORY 'AnalogDevices.EvalClient.dll']);
	NET.addAssembly([INSTALL_DIRECTORY 'AnalogDevices.EvalClient.Installers.dll']);
	NET.addAssembly([CLIENT_DIRECTORY 'AnalogDevices.EvalClient.Fpga9001.Device.dll']);
	import AnalogDevices.Peitho.*;
	import AnalogDevices.EvalClient.*;
	import AnalogDevices.EvalClient.Installers.*;
	import AnalogDevices.EvalClient.Fpga9001.*
	import AnalogDevices.EvalClient.Fpga9001.Device.*
	import binary_9.*
	import binary_10.*
	NET.addAssembly([CLIENT_DIRECTORY 'AnalogDevices.Adrv9001.ProfileTypes.dll']);
	import AnalogDevices.EvalClient.Adrv9001ProfileTypes.*

	[error_code] = obj.fpga9001Device.tdd.Enable_Set(fpga9001_TddSelect_e.FPGA9001_TDDSELECT_DMA_TX1, fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_LOW);
	[error_code] = obj.fpga9001Device.tdd.Enable_Set(fpga9001_TddSelect_e.FPGA9001_TDDSELECT_TX1, fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_LOW);
	[error_code] = obj.fpga9001Device.tdd.Enable_Set(fpga9001_TddSelect_e.FPGA9001_TDDSELECT_DMA_TX2, fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_LOW);
	[error_code] = obj.fpga9001Device.tdd.Enable_Set(fpga9001_TddSelect_e.FPGA9001_TDDSELECT_TX2, fpga9001_TddMode_e.FPGA9001_TDD_ENABLE_LOW);

end

%% Buffered String Builder
function [buff] = build_str_buff(len, s)
	buff = zeros(1, len);
	ba = uint32(s{1});
	for i = 1:length(s{1})
		buff(i) = ba(i);
	end
end
