#include "adrv9001.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v67.1.1*/
/* Firmware: v0.21.0.8*/
/* Profile Generator: v0.50.11.0*/
/* Stream Generator Assembly: v0.7.9.0*/
/* Transceiver Evaluation Software: v0.21.0*/
/* ADRV9001 Plugin: v0.21.0*/

#include "configure.h"

int configure(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;

	AUTOGENERATOR_ERROR_HANDLER(error_code);
	uint32_t gpIntMask_1 = 0;
	error_code = adi_adrv9001_gpio_GpIntMask_Get(adrv9001Device_0, &gpIntMask_1);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_gpio_GpIntMask_Set(adrv9001Device_0, 16);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Tx_AttenuationMode_Set(adrv9001Device_0, ADI_CHANNEL_2, ADI_ADRV9001_TX_ATTENUATION_CONTROL_MODE_SPI);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Tx_Attenuation_Set(adrv9001Device_0, ADI_CHANNEL_2, Adrv9001Params.Tx2Attn);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PowerSavingAndMonitorMode_ChannelPowerSavingCfg_t powerSavingCfg_5 = {
		.channelDisabledPowerDownMode = ADI_ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED, 
		.gpioPinPowerDownMode = ADI_ADRV9001_POWERSAVINGANDMONITORMODE_CHANNEL_MODE_DISABLED};
	error_code = adi_adrv9001_powerSavingAndMonitorMode_ChannelPowerSaving_Configure(adrv9001Device_0, ADI_CHANNEL_2, &powerSavingCfg_5);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_ChannelEnablementDelays_t delays_6 = {
		.riseToOnDelay = 1475, 
		.riseToAnalogOnDelay = 0, 
		.fallToOffDelay = 418, 
		.guardDelay = 0, 
		.holdDelay = 0};
	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &delays_6);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9010_bbdc_LoopGain_Set(adrv9001Device_0, ADI_CHANNEL_2, 65536);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_TrackingCals_t trackingCals_8 = {
		.chanTrackingCalMask = { (adi_adrv9001_TrackingCalibrations_e) 0, ADI_ADRV9001_TRACKING_CAL_TX_QEC | ADI_ADRV9001_TRACKING_CAL_TX_LO_LEAKAGE | ADI_ADRV9001_TRACKING_CAL_TX_DPD_CLGC | ADI_ADRV9001_TRACKING_CAL_RX_BBDC | ADI_ADRV9001_TRACKING_CAL_RX_RFDC | ADI_ADRV9001_TRACKING_CAL_RX_QEC_FIC  }};
	error_code = adi_adrv9001_cals_Tracking_Set(adrv9001Device_0, &trackingCals_8);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_dpd_Configure(adrv9001Device_0, ADI_CHANNEL_2, &Adrv9001Params.Tx2DpdCfg);
	AUTOGENERATOR_ERROR_HANDLER(error_code);

	return error_code;
}
