#include "adrv9001.h"
/* This file contains code automatically generated by a machine. */
/* It has not been independently verified by any human. */
/* All code is provided as-is for example purposes only. */
/* The customer assumes all risks related to the use of this code. */


/* */
/* Silicon Revision: Presumed C0*/
/* */
/* Tx / Rx optimal carrier frequencies: 30 MHz to 6 GHz*/
/* External LO optimal frequencies: 60 MHz to 12 GHz*/
/* */
/* FPGA: v0.0.0*/
/* Device Driver API: v0.0.0*/
/* Device Driver Client: v67.1.1*/
/* Firmware: v0.21.0.8*/
/* Profile Generator: v0.50.11.0*/
/* Stream Generator Assembly: v0.7.9.0*/
/* Transceiver Evaluation Software: v0.21.0*/
/* ADRV9001 Plugin: v0.21.0*/

#include "initialize.h"

int initialize(adi_adrv9001_Device_t * adrv9001Device_0)
{
	int32_t error_code = 0;

	adi_common_ApiVersion_t apiVersion_0 = {
		.major = 0, 
		.minor = 0, 
		.patch = 0};
	error_code = adi_adrv9001_ApiVersion_Get(adrv9001Device_0, &apiVersion_0);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_HwClose(adrv9001Device_0);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_SpiSettings_t spiSettings_5 = {
		.msbFirst = 1, 
		.enSpiStreaming = 0, 
		.autoIncAddrUp = 1, 
		.fourWireMode = 1, 
		.cmosPadDrvStrength = ADI_ADRV9001_CMOSPAD_DRV_STRONG};
	error_code = adi_adrv9001_HwOpen(adrv9001Device_0, &spiSettings_5);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_HwReset(adrv9001Device_0);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_InitAnalog(adrv9001Device_0, (adi_adrv9001_Init_t*)&Adrv9001Params, ADI_ADRV9001_DEVICECLOCKDIVISOR_2);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_AhbSpiBridge_Enable(adrv9001Device_0);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Stream_Image_Write(adrv9001Device_0, 0, initialize_binary_9, 32768, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_Image_Write(adrv9001Device_0, 0, initialize_binary_10, 294912, ADI_ADRV9001_ARM_SINGLE_SPI_WRITE_MODE_STANDARD_BYTES_252);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_Profile_Write(adrv9001Device_0, (adi_adrv9001_Init_t*)&Adrv9001Params);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_PfirProfiles_Write(adrv9001Device_0, (adi_adrv9001_Init_t*)&Adrv9001Params);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_RxLnaConfig_t lnaConfig_13 = {
		.externalLnaPresent = false, 
		.gpioSourceSel = ADI_ADRV9001_GPIO_ANALOG_PIN_NIBBLE_UNASSIGNED, 
		.externalLnaPinSel = ADI_ADRV9001_EXTERNAL_LNA_PIN_RX1_LOWER_RX2_UPPER, 
		.settlingDelay = 0, 
		.numberLnaGainSteps = 0, 
		.lnaGainSteps_mdB = { 0, 0, 0, 0  }, 
		.lnaDigitalGainDelay = 0, 
		.minGainIndex = 0};
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_1, 14, initialize_gainTableRows_13, 13, &lnaConfig_13, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_ORX, ADI_CHANNEL_2, 14, initialize_gainTableRows_14, 13, &lnaConfig_13, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_1, 255, initialize_gainTableRows_15, 69, &lnaConfig_13, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Rx_GainTable_Write(adrv9001Device_0, ADI_RX, ADI_CHANNEL_2, 255, initialize_gainTableRows_16, 69, &lnaConfig_13, ADI_ADRV9001_RX_GAIN_CORRECTION_TABLE);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Tx_AttenuationTable_Write(adrv9001Device_0, 2, 0, initialize_attenTableRows_17, 960);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PowerManagementSettings_t powerManagementSettings_18 = {
		.ldoPowerSavingModes = { ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1, ADI_ADRV9001_LDO_POWER_SAVING_MODE_1  }};
	error_code = adi_adrv9001_powermanagement_Configure(adrv9001Device_0, &powerManagementSettings_18);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_Start(adrv9001Device_0);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_StartStatus_Check(adrv9001Device_0, 5000000);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Tx_OutputPowerBoost_Set(adrv9001Device_0, ADI_CHANNEL_2, Adrv9001Params.Tx2Boost);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_SsiCalibrationCfg_t ssiCalibration_23 = {
		.rxClkDelay = { 0, 0  }, 
		.rxStrobeDelay = { 0, 0  }, 
		.rxIDataDelay = { 0, 0  }, 
		.rxQDataDelay = { 0, 0  }, 
		.txClkDelay = { 0, 0  }, 
		.txRefClkDelay = { 0, 0  }, 
		.txStrobeDelay = { 0, 0  }, 
		.txIDataDelay = { 0, 0  }, 
		.txQDataDelay = { 0, 0  }};
	error_code = adi_adrv9001_Ssi_Delay_Configure(adrv9001Device_0, ADI_ADRV9001_SSI_TYPE_LVDS, &ssiCalibration_23);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_gpio_ControlInit_Configure(adrv9001Device_0, &initialize_gpioCtrlInitCfg_24);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PllLoopFilterCfg_t pllLoopFilterConfig_25 = {
		.effectiveLoopBandwidth_kHz = 0, 
		.loopBandwidth_kHz = 300, 
		.phaseMargin_degrees = 60, 
		.powerScale = 5};
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &pllLoopFilterConfig_25);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &pllLoopFilterConfig_25);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Radio_PllLoopFilter_Set(adrv9001Device_0, ADI_ADRV9001_PLL_AUX, &pllLoopFilterConfig_25);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PowerSavingAndMonitorMode_MonitorModeRssiCfg_t monitorModeRssiCfg_28 = {
		.numberOfMeasurementsToAverage = 4, 
		.measurementsStartPeriod_ms = 1, 
		.detectionThreshold_mdBFS = -80000, 
		.measurementDuration_samples = 10};
	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_Rssi_Configure(adrv9001Device_0, &monitorModeRssiCfg_28);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PowerSavingAndMonitorMode_MonitorModeDmrSearchCfg_t dmrSearchCfg_29 = {
		.pathDelay = 0, 
		.magcorrTh = 400, 
		.detCnt1 = 375, 
		.detCnt2 = 500, 
		.detTgtMin = 800000};
	error_code = adi_adrv9001_powerSavingAndMonitorMode_MonitorMode_DmrSearch_Configure(adrv9001Device_0, &dmrSearchCfg_29);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_RxPortSwitchCfg_t switchConfig_30 = {
		.minFreqPortA_Hz = 890000000, 
		.maxFreqPortA_Hz = 910000000, 
		.minFreqPortB_Hz = 1890000000, 
		.maxFreqPortB_Hz = 1910000000, 
		.enable = false, 
		.manualRxPortSwitch = false};
	error_code = adi_adrv9001_Rx_PortSwitch_Configure(adrv9001Device_0, &switchConfig_30);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Radio_Carrier_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &Adrv9001Params.Lo2Carrier);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_ChannelEnablementDelays_t delays_32 = {
		.riseToOnDelay = 0, 
		.riseToAnalogOnDelay = 0, 
		.fallToOffDelay = 0, 
		.guardDelay = 0, 
		.holdDelay = 0};
	error_code = adi_adrv9001_Radio_ChannelEnablementDelays_Configure(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &delays_32);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_cals_ExternalPathDelay_Set(adrv9001Device_0, ADI_CHANNEL_2, Adrv9001Params.Tx2ExternalPathDelay);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Ssi_PowerDown_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, ADI_ADRV9001_SSI_POWER_DOWN_DISABLED);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_SlewRateLimiterCfg_t config_35 = {
		.srlEnable = false, 
		.srlStatisticsEnable = false, 
		.srlTableSelect = ADI_ADRV9001_SRL_TABLE0, 
		.srlSlewOffset = 0, 
		.srlStatisticsMode = ADI_ADRV9001_SRL_STATISTICS_MIN_SLEW_FACTOR_OBSERVED};
	error_code = adi_adrv9001_Tx_SlewRateLimiter_Configure(adrv9001Device_0, ADI_CHANNEL_2, &config_35);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_dpd_Initial_Configure(adrv9001Device_0, ADI_CHANNEL_2, &Adrv9001Params.Tx2DpdInitCfg);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_PllConfig_t pllConfig_37 = {
		.pllCalibration = ADI_ADRV9001_PLL_CALIBRATION_NORMAL, 
		.pllPower = ADI_ADRV9001_PLL_POWER_LOW};
	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO1, &pllConfig_37);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_Radio_Pll_Configure(adrv9001Device_0, ADI_ADRV9001_PLL_LO2, &pllConfig_37);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	adi_adrv9001_McsDelay_t mcsDelay_39 = {
		.readDelay = 5, 
		.sampleDelay = 0};
	error_code = adi_adrv9001_Mcs_ChannelMcsDelay_Set(adrv9001Device_0, ADI_TX, ADI_CHANNEL_2, &mcsDelay_39);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	error_code = adi_adrv9001_arm_System_Program(adrv9001Device_0, 8);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);
	AUTOGENERATOR_ERROR_HANDLER(error_code);

	return error_code;
}
